// GENERATED by tool/generate_sheets.dart — do not hand-edit.
// Bubble positions are fractions of the page (0.0-1.0), top-left origin —
// page size varies per exam (see each OmrExamTemplate's pageWidthPt/
// pageHeightPt), matching the printed PDFs in /answer_sheets.
// Regenerate with: cd tool && dart run generate_sheets.dart

class BubblePos {
  final String choice;
  final double xFrac;
  final double yFrac;
  const BubblePos(this.choice, this.xFrac, this.yFrac);
}

class OmrSection {
  final String name;
  final int itemCount;
  final Map<int, List<BubblePos>> items;
  const OmrSection({required this.name, required this.itemCount, required this.items});
}

class OmrCorner {
  final double xFrac;
  final double yFrac;
  const OmrCorner(this.xFrac, this.yFrac);
}

/// One of the extra interior registration marks a redesigned sheet prints
/// beyond its 4 corner anchors — a left/right pair straddling the
/// horizontal divider between answer blocks, plus 3 smaller marks on the
/// page's vertical centerline (above the answers, at the divider, below
/// the answers). Unlike [OmrCorner] (always exactly 4, used to fit the
/// sheet's main perspective homography), a template may have zero of
/// these (legacy sheets, TAT) — see [OmrExamTemplate.interiorFiducials].
enum OmrFiducialRole {
  dividerLeft,
  dividerRight,
  centerAboveAnswers,
  centerAtDivider,
  centerBelowAnswers,
}

class OmrFiducial {
  final OmrFiducialRole role;
  final double xFrac;
  final double yFrac;
  /// Half the printed square's side length, in page points — its search
  /// window size differs from the 4 main corners' (see kAtCenterMarkerHalf
  /// vs kAtEdgeMarkerHalf), so the decoder needs it per-mark rather than
  /// assuming one fixed size for every fiducial on the page.
  final double halfSizePt;
  const OmrFiducial(this.role, this.xFrac, this.yFrac, this.halfSizePt);
}

/// A fractional bounding box (0.0-1.0 of the page, top-left origin — same
/// convention as [BubblePos]/[OmrCorner]). Used only to crop a printed
/// hand-written field (Last Name / First Name) out of a perspective-
/// corrected scan for on-device OCR; never used for bubble scoring.
class OmrFieldRect {
  final double xFrac;
  final double yFrac;
  final double widthFrac;
  final double heightFrac;
  const OmrFieldRect(this.xFrac, this.yFrac, this.widthFrac, this.heightFrac);
}

class OmrExamTemplate {
  final String examCode;
  /// Stable identifier for this exact printed geometry — bumped by hand in
  /// kExams whenever a sheet's fiducial/bubble/field layout changes (not
  /// on every regeneration run). Persisted onto each [LocalScan] at scan
  /// time so a later geometry change can never be silently applied when
  /// re-reading an older scan's overlay (see ScannedImageViewerScreen).
  final String templateVersion;
  final double pageWidthPt;
  final double pageHeightPt;
  /// Horizontal radius, in page points, of the printed bubbles — the
  /// decoder samples a region this size around each BubblePos, so it must
  /// match the actual printed geometry rather than being guessed
  /// independently.
  final double bubbleRadiusPt;
  /// Vertical radius — equal to [bubbleRadiusPt] for a true circle (AT/PT),
  /// smaller for QTM/TAT's flattened NDMU-style ovals. Sampling a region
  /// sized to [bubbleRadiusPt] in both directions on an oval bubble
  /// dilutes a genuinely filled bubble's measured fill with blank paper
  /// above/below the actual printed shape — significant enough on its own
  /// to make real marks misread as ambiguous.
  final double bubbleRadiusYPt;
  final List<OmrCorner> cornerMarkers;
  /// Extra interior registration marks beyond the 4 [cornerMarkers] — see
  /// [OmrFiducial]. Empty for a template with no such marks printed
  /// (legacy sheets, TAT): the decoder's local mesh-correction stage is
  /// skipped entirely for those, falling back to the single global
  /// homography exactly as before this field existed.
  final List<OmrFiducial> interiorFiducials;
  final List<OmrSection> sections;
  /// Where the printed, hand-written Last Name / First Name / MI boxes are
  /// on the sheet — see [OmrFieldRect].
  final OmrFieldRect lastNameFieldRect;
  final OmrFieldRect firstNameFieldRect;
  final OmrFieldRect middleInitialFieldRect;
  const OmrExamTemplate({
    required this.examCode,
    required this.templateVersion,
    required this.pageWidthPt,
    required this.pageHeightPt,
    required this.bubbleRadiusPt,
    required this.bubbleRadiusYPt,
    required this.cornerMarkers,
    this.interiorFiducials = const [],
    required this.sections,
    required this.lastNameFieldRect,
    required this.firstNameFieldRect,
    required this.middleInitialFieldRect,
  });
}

final OmrExamTemplate _omrTAT = OmrExamTemplate(
  examCode: "TAT",
  templateVersion: "TAT-v1",
  pageWidthPt: 936.0,
  pageHeightPt: 612.0,
  bubbleRadiusPt: 8.0,
  bubbleRadiusYPt: 6.4,
  cornerMarkers: const [OmrCorner(0.02564, 0.03922), OmrCorner(0.91880, 0.03922), OmrCorner(0.02564, 0.90196), OmrCorner(0.91880, 0.90196)],
  interiorFiducials: const [],
  lastNameFieldRect: const OmrFieldRect(0.04701, 0.13889, 0.29808, 0.02451),
  firstNameFieldRect: const OmrFieldRect(0.34509, 0.13889, 0.26496, 0.02451),
  middleInitialFieldRect: const OmrFieldRect(0.61004, 0.13889, 0.09936, 0.02451),
  sections: const [
    OmrSection(
      name: "Test I",
      itemCount: 30,
      items: {
        1: [BubblePos("A", 0.06838, 0.30392), BubblePos("B", 0.09615, 0.30392), BubblePos("C", 0.12393, 0.30392), BubblePos("D", 0.15171, 0.30392)],
        2: [BubblePos("A", 0.06838, 0.34477), BubblePos("B", 0.09615, 0.34477), BubblePos("C", 0.12393, 0.34477), BubblePos("D", 0.15171, 0.34477)],
        3: [BubblePos("A", 0.06838, 0.38562), BubblePos("B", 0.09615, 0.38562), BubblePos("C", 0.12393, 0.38562), BubblePos("D", 0.15171, 0.38562)],
        4: [BubblePos("A", 0.06838, 0.42647), BubblePos("B", 0.09615, 0.42647), BubblePos("C", 0.12393, 0.42647), BubblePos("D", 0.15171, 0.42647)],
        5: [BubblePos("A", 0.06838, 0.46732), BubblePos("B", 0.09615, 0.46732), BubblePos("C", 0.12393, 0.46732), BubblePos("D", 0.15171, 0.46732)],
        6: [BubblePos("A", 0.06838, 0.50817), BubblePos("B", 0.09615, 0.50817), BubblePos("C", 0.12393, 0.50817), BubblePos("D", 0.15171, 0.50817)],
        7: [BubblePos("A", 0.06838, 0.54902), BubblePos("B", 0.09615, 0.54902), BubblePos("C", 0.12393, 0.54902), BubblePos("D", 0.15171, 0.54902)],
        8: [BubblePos("A", 0.06838, 0.58987), BubblePos("B", 0.09615, 0.58987), BubblePos("C", 0.12393, 0.58987), BubblePos("D", 0.15171, 0.58987)],
        9: [BubblePos("A", 0.06838, 0.63072), BubblePos("B", 0.09615, 0.63072), BubblePos("C", 0.12393, 0.63072), BubblePos("D", 0.15171, 0.63072)],
        10: [BubblePos("A", 0.06838, 0.67157), BubblePos("B", 0.09615, 0.67157), BubblePos("C", 0.12393, 0.67157), BubblePos("D", 0.15171, 0.67157)],
        11: [BubblePos("A", 0.06838, 0.71242), BubblePos("B", 0.09615, 0.71242), BubblePos("C", 0.12393, 0.71242), BubblePos("D", 0.15171, 0.71242)],
        12: [BubblePos("A", 0.06838, 0.75327), BubblePos("B", 0.09615, 0.75327), BubblePos("C", 0.12393, 0.75327), BubblePos("D", 0.15171, 0.75327)],
        13: [BubblePos("A", 0.06838, 0.79412), BubblePos("B", 0.09615, 0.79412), BubblePos("C", 0.12393, 0.79412), BubblePos("D", 0.15171, 0.79412)],
        14: [BubblePos("A", 0.06838, 0.83497), BubblePos("B", 0.09615, 0.83497), BubblePos("C", 0.12393, 0.83497), BubblePos("D", 0.15171, 0.83497)],
        15: [BubblePos("A", 0.06838, 0.87582), BubblePos("B", 0.09615, 0.87582), BubblePos("C", 0.12393, 0.87582), BubblePos("D", 0.15171, 0.87582)],
        16: [BubblePos("A", 0.19872, 0.30392), BubblePos("B", 0.22650, 0.30392), BubblePos("C", 0.25427, 0.30392), BubblePos("D", 0.28205, 0.30392)],
        17: [BubblePos("A", 0.19872, 0.34477), BubblePos("B", 0.22650, 0.34477), BubblePos("C", 0.25427, 0.34477), BubblePos("D", 0.28205, 0.34477)],
        18: [BubblePos("A", 0.19872, 0.38562), BubblePos("B", 0.22650, 0.38562), BubblePos("C", 0.25427, 0.38562), BubblePos("D", 0.28205, 0.38562)],
        19: [BubblePos("A", 0.19872, 0.42647), BubblePos("B", 0.22650, 0.42647), BubblePos("C", 0.25427, 0.42647), BubblePos("D", 0.28205, 0.42647)],
        20: [BubblePos("A", 0.19872, 0.46732), BubblePos("B", 0.22650, 0.46732), BubblePos("C", 0.25427, 0.46732), BubblePos("D", 0.28205, 0.46732)],
        21: [BubblePos("A", 0.19872, 0.50817), BubblePos("B", 0.22650, 0.50817), BubblePos("C", 0.25427, 0.50817), BubblePos("D", 0.28205, 0.50817)],
        22: [BubblePos("A", 0.19872, 0.54902), BubblePos("B", 0.22650, 0.54902), BubblePos("C", 0.25427, 0.54902), BubblePos("D", 0.28205, 0.54902)],
        23: [BubblePos("A", 0.19872, 0.58987), BubblePos("B", 0.22650, 0.58987), BubblePos("C", 0.25427, 0.58987), BubblePos("D", 0.28205, 0.58987)],
        24: [BubblePos("A", 0.19872, 0.63072), BubblePos("B", 0.22650, 0.63072), BubblePos("C", 0.25427, 0.63072), BubblePos("D", 0.28205, 0.63072)],
        25: [BubblePos("A", 0.19872, 0.67157), BubblePos("B", 0.22650, 0.67157), BubblePos("C", 0.25427, 0.67157), BubblePos("D", 0.28205, 0.67157)],
        26: [BubblePos("A", 0.19872, 0.71242), BubblePos("B", 0.22650, 0.71242), BubblePos("C", 0.25427, 0.71242), BubblePos("D", 0.28205, 0.71242)],
        27: [BubblePos("A", 0.19872, 0.75327), BubblePos("B", 0.22650, 0.75327), BubblePos("C", 0.25427, 0.75327), BubblePos("D", 0.28205, 0.75327)],
        28: [BubblePos("A", 0.19872, 0.79412), BubblePos("B", 0.22650, 0.79412), BubblePos("C", 0.25427, 0.79412), BubblePos("D", 0.28205, 0.79412)],
        29: [BubblePos("A", 0.19872, 0.83497), BubblePos("B", 0.22650, 0.83497), BubblePos("C", 0.25427, 0.83497), BubblePos("D", 0.28205, 0.83497)],
        30: [BubblePos("A", 0.19872, 0.87582), BubblePos("B", 0.22650, 0.87582), BubblePos("C", 0.25427, 0.87582), BubblePos("D", 0.28205, 0.87582)],
      },
    ),
    OmrSection(
      name: "Test II",
      itemCount: 80,
      items: {
        1: [BubblePos("T", 0.33761, 0.30392), BubblePos("F", 0.36538, 0.30392)],
        2: [BubblePos("T", 0.33761, 0.34477), BubblePos("F", 0.36538, 0.34477)],
        3: [BubblePos("T", 0.33761, 0.38562), BubblePos("F", 0.36538, 0.38562)],
        4: [BubblePos("T", 0.33761, 0.42647), BubblePos("F", 0.36538, 0.42647)],
        5: [BubblePos("T", 0.33761, 0.46732), BubblePos("F", 0.36538, 0.46732)],
        6: [BubblePos("T", 0.33761, 0.50817), BubblePos("F", 0.36538, 0.50817)],
        7: [BubblePos("T", 0.33761, 0.54902), BubblePos("F", 0.36538, 0.54902)],
        8: [BubblePos("T", 0.33761, 0.58987), BubblePos("F", 0.36538, 0.58987)],
        9: [BubblePos("T", 0.33761, 0.63072), BubblePos("F", 0.36538, 0.63072)],
        10: [BubblePos("T", 0.33761, 0.67157), BubblePos("F", 0.36538, 0.67157)],
        11: [BubblePos("T", 0.33761, 0.71242), BubblePos("F", 0.36538, 0.71242)],
        12: [BubblePos("T", 0.33761, 0.75327), BubblePos("F", 0.36538, 0.75327)],
        13: [BubblePos("T", 0.33761, 0.79412), BubblePos("F", 0.36538, 0.79412)],
        14: [BubblePos("T", 0.33761, 0.83497), BubblePos("F", 0.36538, 0.83497)],
        15: [BubblePos("T", 0.33761, 0.87582), BubblePos("F", 0.36538, 0.87582)],
        16: [BubblePos("T", 0.41239, 0.30392), BubblePos("F", 0.44017, 0.30392)],
        17: [BubblePos("T", 0.41239, 0.34477), BubblePos("F", 0.44017, 0.34477)],
        18: [BubblePos("T", 0.41239, 0.38562), BubblePos("F", 0.44017, 0.38562)],
        19: [BubblePos("T", 0.41239, 0.42647), BubblePos("F", 0.44017, 0.42647)],
        20: [BubblePos("T", 0.41239, 0.46732), BubblePos("F", 0.44017, 0.46732)],
        21: [BubblePos("T", 0.41239, 0.50817), BubblePos("F", 0.44017, 0.50817)],
        22: [BubblePos("T", 0.41239, 0.54902), BubblePos("F", 0.44017, 0.54902)],
        23: [BubblePos("T", 0.41239, 0.58987), BubblePos("F", 0.44017, 0.58987)],
        24: [BubblePos("T", 0.41239, 0.63072), BubblePos("F", 0.44017, 0.63072)],
        25: [BubblePos("T", 0.41239, 0.67157), BubblePos("F", 0.44017, 0.67157)],
        26: [BubblePos("T", 0.41239, 0.71242), BubblePos("F", 0.44017, 0.71242)],
        27: [BubblePos("T", 0.41239, 0.75327), BubblePos("F", 0.44017, 0.75327)],
        28: [BubblePos("T", 0.41239, 0.79412), BubblePos("F", 0.44017, 0.79412)],
        29: [BubblePos("T", 0.41239, 0.83497), BubblePos("F", 0.44017, 0.83497)],
        30: [BubblePos("T", 0.41239, 0.87582), BubblePos("F", 0.44017, 0.87582)],
        31: [BubblePos("T", 0.48718, 0.30392), BubblePos("F", 0.51496, 0.30392)],
        32: [BubblePos("T", 0.48718, 0.34477), BubblePos("F", 0.51496, 0.34477)],
        33: [BubblePos("T", 0.48718, 0.38562), BubblePos("F", 0.51496, 0.38562)],
        34: [BubblePos("T", 0.48718, 0.42647), BubblePos("F", 0.51496, 0.42647)],
        35: [BubblePos("T", 0.48718, 0.46732), BubblePos("F", 0.51496, 0.46732)],
        36: [BubblePos("T", 0.48718, 0.50817), BubblePos("F", 0.51496, 0.50817)],
        37: [BubblePos("T", 0.48718, 0.54902), BubblePos("F", 0.51496, 0.54902)],
        38: [BubblePos("T", 0.48718, 0.58987), BubblePos("F", 0.51496, 0.58987)],
        39: [BubblePos("T", 0.48718, 0.63072), BubblePos("F", 0.51496, 0.63072)],
        40: [BubblePos("T", 0.48718, 0.67157), BubblePos("F", 0.51496, 0.67157)],
        41: [BubblePos("T", 0.48718, 0.71242), BubblePos("F", 0.51496, 0.71242)],
        42: [BubblePos("T", 0.48718, 0.75327), BubblePos("F", 0.51496, 0.75327)],
        43: [BubblePos("T", 0.48718, 0.79412), BubblePos("F", 0.51496, 0.79412)],
        44: [BubblePos("T", 0.48718, 0.83497), BubblePos("F", 0.51496, 0.83497)],
        45: [BubblePos("T", 0.48718, 0.87582), BubblePos("F", 0.51496, 0.87582)],
        46: [BubblePos("T", 0.56197, 0.30392), BubblePos("F", 0.58974, 0.30392)],
        47: [BubblePos("T", 0.56197, 0.34477), BubblePos("F", 0.58974, 0.34477)],
        48: [BubblePos("T", 0.56197, 0.38562), BubblePos("F", 0.58974, 0.38562)],
        49: [BubblePos("T", 0.56197, 0.42647), BubblePos("F", 0.58974, 0.42647)],
        50: [BubblePos("T", 0.56197, 0.46732), BubblePos("F", 0.58974, 0.46732)],
        51: [BubblePos("T", 0.56197, 0.50817), BubblePos("F", 0.58974, 0.50817)],
        52: [BubblePos("T", 0.56197, 0.54902), BubblePos("F", 0.58974, 0.54902)],
        53: [BubblePos("T", 0.56197, 0.58987), BubblePos("F", 0.58974, 0.58987)],
        54: [BubblePos("T", 0.56197, 0.63072), BubblePos("F", 0.58974, 0.63072)],
        55: [BubblePos("T", 0.56197, 0.67157), BubblePos("F", 0.58974, 0.67157)],
        56: [BubblePos("T", 0.56197, 0.71242), BubblePos("F", 0.58974, 0.71242)],
        57: [BubblePos("T", 0.56197, 0.75327), BubblePos("F", 0.58974, 0.75327)],
        58: [BubblePos("T", 0.56197, 0.79412), BubblePos("F", 0.58974, 0.79412)],
        59: [BubblePos("T", 0.56197, 0.83497), BubblePos("F", 0.58974, 0.83497)],
        60: [BubblePos("T", 0.56197, 0.87582), BubblePos("F", 0.58974, 0.87582)],
        61: [BubblePos("T", 0.63675, 0.30392), BubblePos("F", 0.66453, 0.30392)],
        62: [BubblePos("T", 0.63675, 0.34477), BubblePos("F", 0.66453, 0.34477)],
        63: [BubblePos("T", 0.63675, 0.38562), BubblePos("F", 0.66453, 0.38562)],
        64: [BubblePos("T", 0.63675, 0.42647), BubblePos("F", 0.66453, 0.42647)],
        65: [BubblePos("T", 0.63675, 0.46732), BubblePos("F", 0.66453, 0.46732)],
        66: [BubblePos("T", 0.63675, 0.50817), BubblePos("F", 0.66453, 0.50817)],
        67: [BubblePos("T", 0.63675, 0.54902), BubblePos("F", 0.66453, 0.54902)],
        68: [BubblePos("T", 0.63675, 0.58987), BubblePos("F", 0.66453, 0.58987)],
        69: [BubblePos("T", 0.63675, 0.63072), BubblePos("F", 0.66453, 0.63072)],
        70: [BubblePos("T", 0.63675, 0.67157), BubblePos("F", 0.66453, 0.67157)],
        71: [BubblePos("T", 0.63675, 0.71242), BubblePos("F", 0.66453, 0.71242)],
        72: [BubblePos("T", 0.63675, 0.75327), BubblePos("F", 0.66453, 0.75327)],
        73: [BubblePos("T", 0.63675, 0.79412), BubblePos("F", 0.66453, 0.79412)],
        74: [BubblePos("T", 0.63675, 0.83497), BubblePos("F", 0.66453, 0.83497)],
        75: [BubblePos("T", 0.63675, 0.87582), BubblePos("F", 0.66453, 0.87582)],
        76: [BubblePos("T", 0.71154, 0.30392), BubblePos("F", 0.73932, 0.30392)],
        77: [BubblePos("T", 0.71154, 0.34477), BubblePos("F", 0.73932, 0.34477)],
        78: [BubblePos("T", 0.71154, 0.38562), BubblePos("F", 0.73932, 0.38562)],
        79: [BubblePos("T", 0.71154, 0.42647), BubblePos("F", 0.73932, 0.42647)],
        80: [BubblePos("T", 0.71154, 0.46732), BubblePos("F", 0.73932, 0.46732)],
      },
    ),
    OmrSection(
      name: "Test III",
      itemCount: 20,
      items: {
        1: [BubblePos("T", 0.79487, 0.30392), BubblePos("F", 0.82265, 0.30392)],
        2: [BubblePos("T", 0.79487, 0.34477), BubblePos("F", 0.82265, 0.34477)],
        3: [BubblePos("T", 0.79487, 0.38562), BubblePos("F", 0.82265, 0.38562)],
        4: [BubblePos("T", 0.79487, 0.42647), BubblePos("F", 0.82265, 0.42647)],
        5: [BubblePos("T", 0.79487, 0.46732), BubblePos("F", 0.82265, 0.46732)],
        6: [BubblePos("T", 0.79487, 0.50817), BubblePos("F", 0.82265, 0.50817)],
        7: [BubblePos("T", 0.79487, 0.54902), BubblePos("F", 0.82265, 0.54902)],
        8: [BubblePos("T", 0.79487, 0.58987), BubblePos("F", 0.82265, 0.58987)],
        9: [BubblePos("T", 0.79487, 0.63072), BubblePos("F", 0.82265, 0.63072)],
        10: [BubblePos("T", 0.79487, 0.67157), BubblePos("F", 0.82265, 0.67157)],
        11: [BubblePos("T", 0.79487, 0.71242), BubblePos("F", 0.82265, 0.71242)],
        12: [BubblePos("T", 0.79487, 0.75327), BubblePos("F", 0.82265, 0.75327)],
        13: [BubblePos("T", 0.79487, 0.79412), BubblePos("F", 0.82265, 0.79412)],
        14: [BubblePos("T", 0.79487, 0.83497), BubblePos("F", 0.82265, 0.83497)],
        15: [BubblePos("T", 0.79487, 0.87582), BubblePos("F", 0.82265, 0.87582)],
        16: [BubblePos("T", 0.86966, 0.30392), BubblePos("F", 0.89744, 0.30392)],
        17: [BubblePos("T", 0.86966, 0.34477), BubblePos("F", 0.89744, 0.34477)],
        18: [BubblePos("T", 0.86966, 0.38562), BubblePos("F", 0.89744, 0.38562)],
        19: [BubblePos("T", 0.86966, 0.42647), BubblePos("F", 0.89744, 0.42647)],
        20: [BubblePos("T", 0.86966, 0.46732), BubblePos("F", 0.89744, 0.46732)],
      },
    ),
  ],
);

final OmrExamTemplate _omrQTM = OmrExamTemplate(
  examCode: "QTM",
  templateVersion: "QTM-redesign-v1",
  pageWidthPt: 612.0,
  pageHeightPt: 936.0,
  bubbleRadiusPt: 8.0,
  bubbleRadiusYPt: 6.4,
  cornerMarkers: const [OmrCorner(0.03922, 0.02564), OmrCorner(0.86275, 0.02564), OmrCorner(0.03922, 0.96154), OmrCorner(0.86275, 0.96154)],
  interiorFiducials: const [OmrFiducial(OmrFiducialRole.dividerLeft, 0.03922, 0.58761, 7.0), OmrFiducial(OmrFiducialRole.dividerRight, 0.86275, 0.58761, 7.0), OmrFiducial(OmrFiducialRole.centerAboveAnswers, 0.45098, 0.21368, 4.5), OmrFiducial(OmrFiducialRole.centerAtDivider, 0.45098, 0.58761, 4.5), OmrFiducial(OmrFiducialRole.centerBelowAnswers, 0.45098, 0.95085, 4.5)],
  lastNameFieldRect: const OmrFieldRect(0.07190, 0.11752, 0.75817, 0.02137),
  firstNameFieldRect: const OmrFieldRect(0.07190, 0.15598, 0.64444, 0.02137),
  middleInitialFieldRect: const OmrFieldRect(0.71634, 0.15598, 0.11373, 0.02137),
  sections: const [
    OmrSection(
      name: "Section 1",
      itemCount: 10,
      items: {
        1: [BubblePos("A", 0.10458, 0.23504), BubblePos("B", 0.14706, 0.23504), BubblePos("C", 0.18954, 0.23504), BubblePos("D", 0.23203, 0.23504)],
        2: [BubblePos("A", 0.10458, 0.27030), BubblePos("B", 0.14706, 0.27030), BubblePos("C", 0.18954, 0.27030), BubblePos("D", 0.23203, 0.27030)],
        3: [BubblePos("A", 0.10458, 0.30556), BubblePos("B", 0.14706, 0.30556), BubblePos("C", 0.18954, 0.30556), BubblePos("D", 0.23203, 0.30556)],
        4: [BubblePos("A", 0.10458, 0.34081), BubblePos("B", 0.14706, 0.34081), BubblePos("C", 0.18954, 0.34081), BubblePos("D", 0.23203, 0.34081)],
        5: [BubblePos("A", 0.10458, 0.37607), BubblePos("B", 0.14706, 0.37607), BubblePos("C", 0.18954, 0.37607), BubblePos("D", 0.23203, 0.37607)],
        6: [BubblePos("A", 0.10458, 0.41132), BubblePos("B", 0.14706, 0.41132), BubblePos("C", 0.18954, 0.41132), BubblePos("D", 0.23203, 0.41132)],
        7: [BubblePos("A", 0.10458, 0.44658), BubblePos("B", 0.14706, 0.44658), BubblePos("C", 0.18954, 0.44658), BubblePos("D", 0.23203, 0.44658)],
        8: [BubblePos("A", 0.10458, 0.48184), BubblePos("B", 0.14706, 0.48184), BubblePos("C", 0.18954, 0.48184), BubblePos("D", 0.23203, 0.48184)],
        9: [BubblePos("A", 0.10458, 0.51709), BubblePos("B", 0.14706, 0.51709), BubblePos("C", 0.18954, 0.51709), BubblePos("D", 0.23203, 0.51709)],
        10: [BubblePos("A", 0.10458, 0.55235), BubblePos("B", 0.14706, 0.55235), BubblePos("C", 0.18954, 0.55235), BubblePos("D", 0.23203, 0.55235)],
      },
    ),
    OmrSection(
      name: "Section 2",
      itemCount: 10,
      items: {
        11: [BubblePos("A", 0.10458, 0.60577), BubblePos("B", 0.14706, 0.60577), BubblePos("C", 0.18954, 0.60577), BubblePos("D", 0.23203, 0.60577)],
        12: [BubblePos("A", 0.10458, 0.64103), BubblePos("B", 0.14706, 0.64103), BubblePos("C", 0.18954, 0.64103), BubblePos("D", 0.23203, 0.64103)],
        13: [BubblePos("A", 0.10458, 0.67628), BubblePos("B", 0.14706, 0.67628), BubblePos("C", 0.18954, 0.67628), BubblePos("D", 0.23203, 0.67628)],
        14: [BubblePos("A", 0.10458, 0.71154), BubblePos("B", 0.14706, 0.71154), BubblePos("C", 0.18954, 0.71154), BubblePos("D", 0.23203, 0.71154)],
        15: [BubblePos("A", 0.10458, 0.74679), BubblePos("B", 0.14706, 0.74679), BubblePos("C", 0.18954, 0.74679), BubblePos("D", 0.23203, 0.74679)],
        16: [BubblePos("A", 0.10458, 0.78205), BubblePos("B", 0.14706, 0.78205), BubblePos("C", 0.18954, 0.78205), BubblePos("D", 0.23203, 0.78205)],
        17: [BubblePos("A", 0.10458, 0.81731), BubblePos("B", 0.14706, 0.81731), BubblePos("C", 0.18954, 0.81731), BubblePos("D", 0.23203, 0.81731)],
        18: [BubblePos("A", 0.10458, 0.85256), BubblePos("B", 0.14706, 0.85256), BubblePos("C", 0.18954, 0.85256), BubblePos("D", 0.23203, 0.85256)],
        19: [BubblePos("A", 0.10458, 0.88782), BubblePos("B", 0.14706, 0.88782), BubblePos("C", 0.18954, 0.88782), BubblePos("D", 0.23203, 0.88782)],
        20: [BubblePos("A", 0.10458, 0.92308), BubblePos("B", 0.14706, 0.92308), BubblePos("C", 0.18954, 0.92308), BubblePos("D", 0.23203, 0.92308)],
      },
    ),
    OmrSection(
      name: "Section 3",
      itemCount: 10,
      items: {
        21: [BubblePos("A", 0.40359, 0.23504), BubblePos("B", 0.44608, 0.23504), BubblePos("C", 0.48856, 0.23504), BubblePos("D", 0.53105, 0.23504)],
        22: [BubblePos("A", 0.40359, 0.27030), BubblePos("B", 0.44608, 0.27030), BubblePos("C", 0.48856, 0.27030), BubblePos("D", 0.53105, 0.27030)],
        23: [BubblePos("A", 0.40359, 0.30556), BubblePos("B", 0.44608, 0.30556), BubblePos("C", 0.48856, 0.30556), BubblePos("D", 0.53105, 0.30556)],
        24: [BubblePos("A", 0.40359, 0.34081), BubblePos("B", 0.44608, 0.34081), BubblePos("C", 0.48856, 0.34081), BubblePos("D", 0.53105, 0.34081)],
        25: [BubblePos("A", 0.40359, 0.37607), BubblePos("B", 0.44608, 0.37607), BubblePos("C", 0.48856, 0.37607), BubblePos("D", 0.53105, 0.37607)],
        26: [BubblePos("A", 0.40359, 0.41132), BubblePos("B", 0.44608, 0.41132), BubblePos("C", 0.48856, 0.41132), BubblePos("D", 0.53105, 0.41132)],
        27: [BubblePos("A", 0.40359, 0.44658), BubblePos("B", 0.44608, 0.44658), BubblePos("C", 0.48856, 0.44658), BubblePos("D", 0.53105, 0.44658)],
        28: [BubblePos("A", 0.40359, 0.48184), BubblePos("B", 0.44608, 0.48184), BubblePos("C", 0.48856, 0.48184), BubblePos("D", 0.53105, 0.48184)],
        29: [BubblePos("A", 0.40359, 0.51709), BubblePos("B", 0.44608, 0.51709), BubblePos("C", 0.48856, 0.51709), BubblePos("D", 0.53105, 0.51709)],
        30: [BubblePos("A", 0.40359, 0.55235), BubblePos("B", 0.44608, 0.55235), BubblePos("C", 0.48856, 0.55235), BubblePos("D", 0.53105, 0.55235)],
      },
    ),
    OmrSection(
      name: "Section 4",
      itemCount: 10,
      items: {
        31: [BubblePos("A", 0.40359, 0.60577), BubblePos("B", 0.44608, 0.60577), BubblePos("C", 0.48856, 0.60577), BubblePos("D", 0.53105, 0.60577)],
        32: [BubblePos("A", 0.40359, 0.64103), BubblePos("B", 0.44608, 0.64103), BubblePos("C", 0.48856, 0.64103), BubblePos("D", 0.53105, 0.64103)],
        33: [BubblePos("A", 0.40359, 0.67628), BubblePos("B", 0.44608, 0.67628), BubblePos("C", 0.48856, 0.67628), BubblePos("D", 0.53105, 0.67628)],
        34: [BubblePos("A", 0.40359, 0.71154), BubblePos("B", 0.44608, 0.71154), BubblePos("C", 0.48856, 0.71154), BubblePos("D", 0.53105, 0.71154)],
        35: [BubblePos("A", 0.40359, 0.74679), BubblePos("B", 0.44608, 0.74679), BubblePos("C", 0.48856, 0.74679), BubblePos("D", 0.53105, 0.74679)],
        36: [BubblePos("A", 0.40359, 0.78205), BubblePos("B", 0.44608, 0.78205), BubblePos("C", 0.48856, 0.78205), BubblePos("D", 0.53105, 0.78205)],
        37: [BubblePos("A", 0.40359, 0.81731), BubblePos("B", 0.44608, 0.81731), BubblePos("C", 0.48856, 0.81731), BubblePos("D", 0.53105, 0.81731)],
        38: [BubblePos("A", 0.40359, 0.85256), BubblePos("B", 0.44608, 0.85256), BubblePos("C", 0.48856, 0.85256), BubblePos("D", 0.53105, 0.85256)],
        39: [BubblePos("A", 0.40359, 0.88782), BubblePos("B", 0.44608, 0.88782), BubblePos("C", 0.48856, 0.88782), BubblePos("D", 0.53105, 0.88782)],
        40: [BubblePos("A", 0.40359, 0.92308), BubblePos("B", 0.44608, 0.92308), BubblePos("C", 0.48856, 0.92308), BubblePos("D", 0.53105, 0.92308)],
      },
    ),
    OmrSection(
      name: "Section 5",
      itemCount: 10,
      items: {
        41: [BubblePos("A", 0.70261, 0.23504), BubblePos("B", 0.74510, 0.23504), BubblePos("C", 0.78758, 0.23504), BubblePos("D", 0.83007, 0.23504)],
        42: [BubblePos("A", 0.70261, 0.27030), BubblePos("B", 0.74510, 0.27030), BubblePos("C", 0.78758, 0.27030), BubblePos("D", 0.83007, 0.27030)],
        43: [BubblePos("A", 0.70261, 0.30556), BubblePos("B", 0.74510, 0.30556), BubblePos("C", 0.78758, 0.30556), BubblePos("D", 0.83007, 0.30556)],
        44: [BubblePos("A", 0.70261, 0.34081), BubblePos("B", 0.74510, 0.34081), BubblePos("C", 0.78758, 0.34081), BubblePos("D", 0.83007, 0.34081)],
        45: [BubblePos("A", 0.70261, 0.37607), BubblePos("B", 0.74510, 0.37607), BubblePos("C", 0.78758, 0.37607), BubblePos("D", 0.83007, 0.37607)],
        46: [BubblePos("A", 0.70261, 0.41132), BubblePos("B", 0.74510, 0.41132), BubblePos("C", 0.78758, 0.41132), BubblePos("D", 0.83007, 0.41132)],
        47: [BubblePos("A", 0.70261, 0.44658), BubblePos("B", 0.74510, 0.44658), BubblePos("C", 0.78758, 0.44658), BubblePos("D", 0.83007, 0.44658)],
        48: [BubblePos("A", 0.70261, 0.48184), BubblePos("B", 0.74510, 0.48184), BubblePos("C", 0.78758, 0.48184), BubblePos("D", 0.83007, 0.48184)],
        49: [BubblePos("A", 0.70261, 0.51709), BubblePos("B", 0.74510, 0.51709), BubblePos("C", 0.78758, 0.51709), BubblePos("D", 0.83007, 0.51709)],
        50: [BubblePos("A", 0.70261, 0.55235), BubblePos("B", 0.74510, 0.55235), BubblePos("C", 0.78758, 0.55235), BubblePos("D", 0.83007, 0.55235)],
      },
    ),
    OmrSection(
      name: "Section 6",
      itemCount: 10,
      items: {
        51: [BubblePos("A", 0.70261, 0.60577), BubblePos("B", 0.74510, 0.60577), BubblePos("C", 0.78758, 0.60577), BubblePos("D", 0.83007, 0.60577)],
        52: [BubblePos("A", 0.70261, 0.64103), BubblePos("B", 0.74510, 0.64103), BubblePos("C", 0.78758, 0.64103), BubblePos("D", 0.83007, 0.64103)],
        53: [BubblePos("A", 0.70261, 0.67628), BubblePos("B", 0.74510, 0.67628), BubblePos("C", 0.78758, 0.67628), BubblePos("D", 0.83007, 0.67628)],
        54: [BubblePos("A", 0.70261, 0.71154), BubblePos("B", 0.74510, 0.71154), BubblePos("C", 0.78758, 0.71154), BubblePos("D", 0.83007, 0.71154)],
        55: [BubblePos("A", 0.70261, 0.74679), BubblePos("B", 0.74510, 0.74679), BubblePos("C", 0.78758, 0.74679), BubblePos("D", 0.83007, 0.74679)],
        56: [BubblePos("A", 0.70261, 0.78205), BubblePos("B", 0.74510, 0.78205), BubblePos("C", 0.78758, 0.78205), BubblePos("D", 0.83007, 0.78205)],
        57: [BubblePos("A", 0.70261, 0.81731), BubblePos("B", 0.74510, 0.81731), BubblePos("C", 0.78758, 0.81731), BubblePos("D", 0.83007, 0.81731)],
        58: [BubblePos("A", 0.70261, 0.85256), BubblePos("B", 0.74510, 0.85256), BubblePos("C", 0.78758, 0.85256), BubblePos("D", 0.83007, 0.85256)],
        59: [BubblePos("A", 0.70261, 0.88782), BubblePos("B", 0.74510, 0.88782), BubblePos("C", 0.78758, 0.88782), BubblePos("D", 0.83007, 0.88782)],
        60: [BubblePos("A", 0.70261, 0.92308), BubblePos("B", 0.74510, 0.92308), BubblePos("C", 0.78758, 0.92308), BubblePos("D", 0.83007, 0.92308)],
      },
    ),
  ],
);

final OmrExamTemplate _omrAT = OmrExamTemplate(
  examCode: "AT",
  templateVersion: "AT-redesign-v1",
  pageWidthPt: 595.28,
  pageHeightPt: 841.89,
  bubbleRadiusPt: 8.0,
  bubbleRadiusYPt: 8.0,
  cornerMarkers: const [OmrCorner(0.04032, 0.02851), OmrCorner(0.86682, 0.02851), OmrCorner(0.04032, 0.95499), OmrCorner(0.86682, 0.95499)],
  interiorFiducials: const [OmrFiducial(OmrFiducialRole.dividerLeft, 0.04032, 0.59034, 7.0), OmrFiducial(OmrFiducialRole.dividerRight, 0.86682, 0.59034, 7.0), OmrFiducial(OmrFiducialRole.centerAboveAnswers, 0.45357, 0.22568, 4.5), OmrFiducial(OmrFiducialRole.centerAtDivider, 0.45357, 0.59034, 4.5), OmrFiducial(OmrFiducialRole.centerBelowAnswers, 0.45357, 0.94312, 4.5)],
  lastNameFieldRect: const OmrFieldRect(0.07391, 0.12353, 0.75931, 0.02376),
  firstNameFieldRect: const OmrFieldRect(0.07391, 0.16629, 0.64541, 0.02376),
  middleInitialFieldRect: const OmrFieldRect(0.71933, 0.16629, 0.11390, 0.02376),
  sections: const [
    OmrSection(
      name: "Section 1",
      itemCount: 12,
      items: {
        1: [BubblePos("A", 0.10751, 0.24944), BubblePos("B", 0.15119, 0.24944), BubblePos("C", 0.19487, 0.24944), BubblePos("D", 0.23854, 0.24944), BubblePos("E", 0.28222, 0.24944)],
        2: [BubblePos("F", 0.10751, 0.27676), BubblePos("G", 0.15119, 0.27676), BubblePos("H", 0.19487, 0.27676), BubblePos("J", 0.23854, 0.27676), BubblePos("K", 0.28222, 0.27676)],
        3: [BubblePos("A", 0.10751, 0.30408), BubblePos("B", 0.15119, 0.30408), BubblePos("C", 0.19487, 0.30408), BubblePos("D", 0.23854, 0.30408), BubblePos("E", 0.28222, 0.30408)],
        4: [BubblePos("F", 0.10751, 0.33140), BubblePos("G", 0.15119, 0.33140), BubblePos("H", 0.19487, 0.33140), BubblePos("J", 0.23854, 0.33140), BubblePos("K", 0.28222, 0.33140)],
        5: [BubblePos("A", 0.10751, 0.35872), BubblePos("B", 0.15119, 0.35872), BubblePos("C", 0.19487, 0.35872), BubblePos("D", 0.23854, 0.35872), BubblePos("E", 0.28222, 0.35872)],
        6: [BubblePos("F", 0.10751, 0.38604), BubblePos("G", 0.15119, 0.38604), BubblePos("H", 0.19487, 0.38604), BubblePos("J", 0.23854, 0.38604), BubblePos("K", 0.28222, 0.38604)],
        7: [BubblePos("A", 0.10751, 0.41336), BubblePos("B", 0.15119, 0.41336), BubblePos("C", 0.19487, 0.41336), BubblePos("D", 0.23854, 0.41336), BubblePos("E", 0.28222, 0.41336)],
        8: [BubblePos("F", 0.10751, 0.44068), BubblePos("G", 0.15119, 0.44068), BubblePos("H", 0.19487, 0.44068), BubblePos("J", 0.23854, 0.44068), BubblePos("K", 0.28222, 0.44068)],
        9: [BubblePos("A", 0.10751, 0.46799), BubblePos("B", 0.15119, 0.46799), BubblePos("C", 0.19487, 0.46799), BubblePos("D", 0.23854, 0.46799), BubblePos("E", 0.28222, 0.46799)],
        10: [BubblePos("F", 0.10751, 0.49531), BubblePos("G", 0.15119, 0.49531), BubblePos("H", 0.19487, 0.49531), BubblePos("J", 0.23854, 0.49531), BubblePos("K", 0.28222, 0.49531)],
        11: [BubblePos("A", 0.10751, 0.52263), BubblePos("B", 0.15119, 0.52263), BubblePos("C", 0.19487, 0.52263), BubblePos("D", 0.23854, 0.52263), BubblePos("E", 0.28222, 0.52263)],
        12: [BubblePos("F", 0.10751, 0.54995), BubblePos("G", 0.15119, 0.54995), BubblePos("H", 0.19487, 0.54995), BubblePos("J", 0.23854, 0.54995), BubblePos("K", 0.28222, 0.54995)],
      },
    ),
    OmrSection(
      name: "Section 2",
      itemCount: 12,
      items: {
        13: [BubblePos("A", 0.38301, 0.24944), BubblePos("B", 0.42669, 0.24944), BubblePos("C", 0.47037, 0.24944), BubblePos("D", 0.51404, 0.24944), BubblePos("E", 0.55772, 0.24944)],
        14: [BubblePos("F", 0.38301, 0.27676), BubblePos("G", 0.42669, 0.27676), BubblePos("H", 0.47037, 0.27676), BubblePos("J", 0.51404, 0.27676), BubblePos("K", 0.55772, 0.27676)],
        15: [BubblePos("A", 0.38301, 0.30408), BubblePos("B", 0.42669, 0.30408), BubblePos("C", 0.47037, 0.30408), BubblePos("D", 0.51404, 0.30408), BubblePos("E", 0.55772, 0.30408)],
        16: [BubblePos("F", 0.38301, 0.33140), BubblePos("G", 0.42669, 0.33140), BubblePos("H", 0.47037, 0.33140), BubblePos("J", 0.51404, 0.33140), BubblePos("K", 0.55772, 0.33140)],
        17: [BubblePos("A", 0.38301, 0.35872), BubblePos("B", 0.42669, 0.35872), BubblePos("C", 0.47037, 0.35872), BubblePos("D", 0.51404, 0.35872), BubblePos("E", 0.55772, 0.35872)],
        18: [BubblePos("F", 0.38301, 0.38604), BubblePos("G", 0.42669, 0.38604), BubblePos("H", 0.47037, 0.38604), BubblePos("J", 0.51404, 0.38604), BubblePos("K", 0.55772, 0.38604)],
        19: [BubblePos("A", 0.38301, 0.41336), BubblePos("B", 0.42669, 0.41336), BubblePos("C", 0.47037, 0.41336), BubblePos("D", 0.51404, 0.41336), BubblePos("E", 0.55772, 0.41336)],
        20: [BubblePos("F", 0.38301, 0.44068), BubblePos("G", 0.42669, 0.44068), BubblePos("H", 0.47037, 0.44068), BubblePos("J", 0.51404, 0.44068), BubblePos("K", 0.55772, 0.44068)],
        21: [BubblePos("A", 0.38301, 0.46799), BubblePos("B", 0.42669, 0.46799), BubblePos("C", 0.47037, 0.46799), BubblePos("D", 0.51404, 0.46799), BubblePos("E", 0.55772, 0.46799)],
        22: [BubblePos("F", 0.38301, 0.49531), BubblePos("G", 0.42669, 0.49531), BubblePos("H", 0.47037, 0.49531), BubblePos("J", 0.51404, 0.49531), BubblePos("K", 0.55772, 0.49531)],
        23: [BubblePos("A", 0.38301, 0.52263), BubblePos("B", 0.42669, 0.52263), BubblePos("C", 0.47037, 0.52263), BubblePos("D", 0.51404, 0.52263), BubblePos("E", 0.55772, 0.52263)],
        24: [BubblePos("F", 0.38301, 0.54995), BubblePos("G", 0.42669, 0.54995), BubblePos("H", 0.47037, 0.54995), BubblePos("J", 0.51404, 0.54995), BubblePos("K", 0.55772, 0.54995)],
      },
    ),
    OmrSection(
      name: "Section 3",
      itemCount: 12,
      items: {
        25: [BubblePos("A", 0.65851, 0.24944), BubblePos("B", 0.70219, 0.24944), BubblePos("C", 0.74587, 0.24944), BubblePos("D", 0.78954, 0.24944), BubblePos("E", 0.83322, 0.24944)],
        26: [BubblePos("F", 0.65851, 0.27676), BubblePos("G", 0.70219, 0.27676), BubblePos("H", 0.74587, 0.27676), BubblePos("J", 0.78954, 0.27676), BubblePos("K", 0.83322, 0.27676)],
        27: [BubblePos("A", 0.65851, 0.30408), BubblePos("B", 0.70219, 0.30408), BubblePos("C", 0.74587, 0.30408), BubblePos("D", 0.78954, 0.30408), BubblePos("E", 0.83322, 0.30408)],
        28: [BubblePos("F", 0.65851, 0.33140), BubblePos("G", 0.70219, 0.33140), BubblePos("H", 0.74587, 0.33140), BubblePos("J", 0.78954, 0.33140), BubblePos("K", 0.83322, 0.33140)],
        29: [BubblePos("A", 0.65851, 0.35872), BubblePos("B", 0.70219, 0.35872), BubblePos("C", 0.74587, 0.35872), BubblePos("D", 0.78954, 0.35872), BubblePos("E", 0.83322, 0.35872)],
        30: [BubblePos("F", 0.65851, 0.38604), BubblePos("G", 0.70219, 0.38604), BubblePos("H", 0.74587, 0.38604), BubblePos("J", 0.78954, 0.38604), BubblePos("K", 0.83322, 0.38604)],
        31: [BubblePos("A", 0.65851, 0.41336), BubblePos("B", 0.70219, 0.41336), BubblePos("C", 0.74587, 0.41336), BubblePos("D", 0.78954, 0.41336), BubblePos("E", 0.83322, 0.41336)],
        32: [BubblePos("F", 0.65851, 0.44068), BubblePos("G", 0.70219, 0.44068), BubblePos("H", 0.74587, 0.44068), BubblePos("J", 0.78954, 0.44068), BubblePos("K", 0.83322, 0.44068)],
        33: [BubblePos("A", 0.65851, 0.46799), BubblePos("B", 0.70219, 0.46799), BubblePos("C", 0.74587, 0.46799), BubblePos("D", 0.78954, 0.46799), BubblePos("E", 0.83322, 0.46799)],
        34: [BubblePos("F", 0.65851, 0.49531), BubblePos("G", 0.70219, 0.49531), BubblePos("H", 0.74587, 0.49531), BubblePos("J", 0.78954, 0.49531), BubblePos("K", 0.83322, 0.49531)],
        35: [BubblePos("A", 0.65851, 0.52263), BubblePos("B", 0.70219, 0.52263), BubblePos("C", 0.74587, 0.52263), BubblePos("D", 0.78954, 0.52263), BubblePos("E", 0.83322, 0.52263)],
        36: [BubblePos("F", 0.65851, 0.54995), BubblePos("G", 0.70219, 0.54995), BubblePos("H", 0.74587, 0.54995), BubblePos("J", 0.78954, 0.54995), BubblePos("K", 0.83322, 0.54995)],
      },
    ),
    OmrSection(
      name: "Section 4",
      itemCount: 12,
      items: {
        37: [BubblePos("A", 0.10751, 0.61172), BubblePos("B", 0.15119, 0.61172), BubblePos("C", 0.19487, 0.61172), BubblePos("D", 0.23854, 0.61172), BubblePos("E", 0.28222, 0.61172)],
        38: [BubblePos("F", 0.10751, 0.63904), BubblePos("G", 0.15119, 0.63904), BubblePos("H", 0.19487, 0.63904), BubblePos("J", 0.23854, 0.63904), BubblePos("K", 0.28222, 0.63904)],
        39: [BubblePos("A", 0.10751, 0.66636), BubblePos("B", 0.15119, 0.66636), BubblePos("C", 0.19487, 0.66636), BubblePos("D", 0.23854, 0.66636), BubblePos("E", 0.28222, 0.66636)],
        40: [BubblePos("F", 0.10751, 0.69368), BubblePos("G", 0.15119, 0.69368), BubblePos("H", 0.19487, 0.69368), BubblePos("J", 0.23854, 0.69368), BubblePos("K", 0.28222, 0.69368)],
        41: [BubblePos("A", 0.10751, 0.72100), BubblePos("B", 0.15119, 0.72100), BubblePos("C", 0.19487, 0.72100), BubblePos("D", 0.23854, 0.72100), BubblePos("E", 0.28222, 0.72100)],
        42: [BubblePos("F", 0.10751, 0.74832), BubblePos("G", 0.15119, 0.74832), BubblePos("H", 0.19487, 0.74832), BubblePos("J", 0.23854, 0.74832), BubblePos("K", 0.28222, 0.74832)],
        43: [BubblePos("A", 0.10751, 0.77564), BubblePos("B", 0.15119, 0.77564), BubblePos("C", 0.19487, 0.77564), BubblePos("D", 0.23854, 0.77564), BubblePos("E", 0.28222, 0.77564)],
        44: [BubblePos("F", 0.10751, 0.80296), BubblePos("G", 0.15119, 0.80296), BubblePos("H", 0.19487, 0.80296), BubblePos("J", 0.23854, 0.80296), BubblePos("K", 0.28222, 0.80296)],
        45: [BubblePos("A", 0.10751, 0.83027), BubblePos("B", 0.15119, 0.83027), BubblePos("C", 0.19487, 0.83027), BubblePos("D", 0.23854, 0.83027), BubblePos("E", 0.28222, 0.83027)],
        46: [BubblePos("F", 0.10751, 0.85759), BubblePos("G", 0.15119, 0.85759), BubblePos("H", 0.19487, 0.85759), BubblePos("J", 0.23854, 0.85759), BubblePos("K", 0.28222, 0.85759)],
        47: [BubblePos("A", 0.10751, 0.88491), BubblePos("B", 0.15119, 0.88491), BubblePos("C", 0.19487, 0.88491), BubblePos("D", 0.23854, 0.88491), BubblePos("E", 0.28222, 0.88491)],
        48: [BubblePos("F", 0.10751, 0.91223), BubblePos("G", 0.15119, 0.91223), BubblePos("H", 0.19487, 0.91223), BubblePos("J", 0.23854, 0.91223), BubblePos("K", 0.28222, 0.91223)],
      },
    ),
    OmrSection(
      name: "Section 5",
      itemCount: 12,
      items: {
        49: [BubblePos("A", 0.38301, 0.61172), BubblePos("B", 0.42669, 0.61172), BubblePos("C", 0.47037, 0.61172), BubblePos("D", 0.51404, 0.61172), BubblePos("E", 0.55772, 0.61172)],
        50: [BubblePos("F", 0.38301, 0.63904), BubblePos("G", 0.42669, 0.63904), BubblePos("H", 0.47037, 0.63904), BubblePos("J", 0.51404, 0.63904), BubblePos("K", 0.55772, 0.63904)],
        51: [BubblePos("A", 0.38301, 0.66636), BubblePos("B", 0.42669, 0.66636), BubblePos("C", 0.47037, 0.66636), BubblePos("D", 0.51404, 0.66636), BubblePos("E", 0.55772, 0.66636)],
        52: [BubblePos("F", 0.38301, 0.69368), BubblePos("G", 0.42669, 0.69368), BubblePos("H", 0.47037, 0.69368), BubblePos("J", 0.51404, 0.69368), BubblePos("K", 0.55772, 0.69368)],
        53: [BubblePos("A", 0.38301, 0.72100), BubblePos("B", 0.42669, 0.72100), BubblePos("C", 0.47037, 0.72100), BubblePos("D", 0.51404, 0.72100), BubblePos("E", 0.55772, 0.72100)],
        54: [BubblePos("F", 0.38301, 0.74832), BubblePos("G", 0.42669, 0.74832), BubblePos("H", 0.47037, 0.74832), BubblePos("J", 0.51404, 0.74832), BubblePos("K", 0.55772, 0.74832)],
        55: [BubblePos("A", 0.38301, 0.77564), BubblePos("B", 0.42669, 0.77564), BubblePos("C", 0.47037, 0.77564), BubblePos("D", 0.51404, 0.77564), BubblePos("E", 0.55772, 0.77564)],
        56: [BubblePos("F", 0.38301, 0.80296), BubblePos("G", 0.42669, 0.80296), BubblePos("H", 0.47037, 0.80296), BubblePos("J", 0.51404, 0.80296), BubblePos("K", 0.55772, 0.80296)],
        57: [BubblePos("A", 0.38301, 0.83027), BubblePos("B", 0.42669, 0.83027), BubblePos("C", 0.47037, 0.83027), BubblePos("D", 0.51404, 0.83027), BubblePos("E", 0.55772, 0.83027)],
        58: [BubblePos("F", 0.38301, 0.85759), BubblePos("G", 0.42669, 0.85759), BubblePos("H", 0.47037, 0.85759), BubblePos("J", 0.51404, 0.85759), BubblePos("K", 0.55772, 0.85759)],
        59: [BubblePos("A", 0.38301, 0.88491), BubblePos("B", 0.42669, 0.88491), BubblePos("C", 0.47037, 0.88491), BubblePos("D", 0.51404, 0.88491), BubblePos("E", 0.55772, 0.88491)],
        60: [BubblePos("F", 0.38301, 0.91223), BubblePos("G", 0.42669, 0.91223), BubblePos("H", 0.47037, 0.91223), BubblePos("J", 0.51404, 0.91223), BubblePos("K", 0.55772, 0.91223)],
      },
    ),
    OmrSection(
      name: "Section 6",
      itemCount: 12,
      items: {
        61: [BubblePos("A", 0.65851, 0.61172), BubblePos("B", 0.70219, 0.61172), BubblePos("C", 0.74587, 0.61172), BubblePos("D", 0.78954, 0.61172), BubblePos("E", 0.83322, 0.61172)],
        62: [BubblePos("F", 0.65851, 0.63904), BubblePos("G", 0.70219, 0.63904), BubblePos("H", 0.74587, 0.63904), BubblePos("J", 0.78954, 0.63904), BubblePos("K", 0.83322, 0.63904)],
        63: [BubblePos("A", 0.65851, 0.66636), BubblePos("B", 0.70219, 0.66636), BubblePos("C", 0.74587, 0.66636), BubblePos("D", 0.78954, 0.66636), BubblePos("E", 0.83322, 0.66636)],
        64: [BubblePos("F", 0.65851, 0.69368), BubblePos("G", 0.70219, 0.69368), BubblePos("H", 0.74587, 0.69368), BubblePos("J", 0.78954, 0.69368), BubblePos("K", 0.83322, 0.69368)],
        65: [BubblePos("A", 0.65851, 0.72100), BubblePos("B", 0.70219, 0.72100), BubblePos("C", 0.74587, 0.72100), BubblePos("D", 0.78954, 0.72100), BubblePos("E", 0.83322, 0.72100)],
        66: [BubblePos("F", 0.65851, 0.74832), BubblePos("G", 0.70219, 0.74832), BubblePos("H", 0.74587, 0.74832), BubblePos("J", 0.78954, 0.74832), BubblePos("K", 0.83322, 0.74832)],
        67: [BubblePos("A", 0.65851, 0.77564), BubblePos("B", 0.70219, 0.77564), BubblePos("C", 0.74587, 0.77564), BubblePos("D", 0.78954, 0.77564), BubblePos("E", 0.83322, 0.77564)],
        68: [BubblePos("F", 0.65851, 0.80296), BubblePos("G", 0.70219, 0.80296), BubblePos("H", 0.74587, 0.80296), BubblePos("J", 0.78954, 0.80296), BubblePos("K", 0.83322, 0.80296)],
        69: [BubblePos("A", 0.65851, 0.83027), BubblePos("B", 0.70219, 0.83027), BubblePos("C", 0.74587, 0.83027), BubblePos("D", 0.78954, 0.83027), BubblePos("E", 0.83322, 0.83027)],
        70: [BubblePos("F", 0.65851, 0.85759), BubblePos("G", 0.70219, 0.85759), BubblePos("H", 0.74587, 0.85759), BubblePos("J", 0.78954, 0.85759), BubblePos("K", 0.83322, 0.85759)],
        71: [BubblePos("A", 0.65851, 0.88491), BubblePos("B", 0.70219, 0.88491), BubblePos("C", 0.74587, 0.88491), BubblePos("D", 0.78954, 0.88491), BubblePos("E", 0.83322, 0.88491)],
        72: [BubblePos("F", 0.65851, 0.91223), BubblePos("G", 0.70219, 0.91223), BubblePos("H", 0.74587, 0.91223), BubblePos("J", 0.78954, 0.91223), BubblePos("K", 0.83322, 0.91223)],
      },
    ),
  ],
);

final Map<String, OmrExamTemplate> omrTemplates = {
  "TAT": _omrTAT,
  "QTM": _omrQTM,
  "AT": _omrAT,
};
