// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Firebase is not configured for Windows - use Android, iOS, or Web instead.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKByZ2rhVSZxEb1OiqeAb3zhkC9GCKXaQ',
    appId: '1:204847946991:web:6a65308c9fe1f4b868cf1a',
    messagingSenderId: '204847946991',
    projectId: 'guidegrade-470ea',
    authDomain: 'guidegrade-470ea.firebaseapp.com',
    storageBucket: 'guidegrade-470ea.firebasestorage.app',
    measurementId: 'G-K5MFYGQZ29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeytoCvHubnin3AMCQX-5L0tin9QwbFMQ',
    appId: '1:204847946991:android:57a303a556f540da68cf1a',
    messagingSenderId: '204847946991',
    projectId: 'guidegrade-470ea',
    storageBucket: 'guidegrade-470ea.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlGG3Ko5vu60jVSH2Akie6fpbSJ8eAwo',
    appId: '1:204847946991:ios:c0fca4549e04a4da68cf1a',
    messagingSenderId: '204847946991',
    projectId: 'guidegrade-470ea',
    storageBucket: 'guidegrade-470ea.firebasestorage.app',
    androidClientId:
        '204847946991-itunqskqiq5l6p3oimgkkihkn97b32o6.apps.googleusercontent.com',
    iosClientId:
        '204847946991-akhevlhev2sqcnpe69151bnbq3qun4nk.apps.googleusercontent.com',
    iosBundleId: 'com.guidegrade.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlGG3Ko5vu60jVSH2Akie6fpbSJ8eAwo',
    appId: '1:204847946991:ios:9cbb1a94974f076168cf1a',
    messagingSenderId: '204847946991',
    projectId: 'guidegrade-470ea',
    storageBucket: 'guidegrade-470ea.firebasestorage.app',
    androidClientId:
        '204847946991-itunqskqiq5l6p3oimgkkihkn97b32o6.apps.googleusercontent.com',
    iosClientId:
        '204847946991-u1ci700vovarna8v97m89lou4vlpvu91.apps.googleusercontent.com',
    iosBundleId: 'com.example.guidegrade',
  );
}
