// Generates lib/core/omr/omr_template_tat_v5.dart from the v5 portrait TAT
// geometry JSON (the source of truth for that printed sheet).
//
//   dart tool/import_tat_v5_geometry.dart [path/to/TAT-portrait-proposed-v5.geometry.json]
//
// Pure Dart (no OpenCV). Positions in the JSON are PDF points, top-left
// origin; the template stores fractions of the page, like every other sheet.
// Deterministic: running it twice writes identical bytes.
import 'dart:convert';
import 'dart:io';

const _defaultJson = 'tool/data/TAT-portrait-v5.geometry.json';
const _outPath = 'lib/core/omr/omr_template_tat_v5.dart';

/// JSON fiducial role -> (OmrFiducialRole name or null for a corner).
/// The three big marks reuse the roles AT/QTM already give their equivalents
/// (a side pair at the divider row, one mark on the vertical centre line at
/// that row); the seven small marks above the answer groups get their own.
const _roleMap = {
  'topLeft': null,
  'topRight': null,
  'bottomLeft': null,
  'bottomRight': null,
  'midLeft': 'dividerLeft',
  'midRight': 'dividerRight',
  'centerTestII23And43': 'centerAtDivider',
  'aboveTestI1': 'tatAboveI1',
  'aboveTestI11': 'tatAboveI11',
  'aboveTestI21': 'tatAboveI21',
  'aboveTestII21': 'tatAboveII21',
  'aboveTestII41': 'tatAboveII41',
  'aboveTestIII6': 'tatAboveIII6',
  'aboveTestIII11': 'tatAboveIII11',
};

String _f(double v) => v.toStringAsFixed(5);

void main(List<String> args) {
  final jsonPath = args.isNotEmpty ? args.first : _defaultJson;
  final data = jsonDecode(File(jsonPath).readAsStringSync()) as Map<String, dynamic>;
  final w = (data['pageWidth'] as num).toDouble();
  final h = (data['pageHeight'] as num).toDouble();

  // --- fiducials ---------------------------------------------------------
  final byRole = {
    for (final f in data['fiducials'] as List) (f as Map<String, dynamic>)['role'] as String: f,
  };
  for (final role in _roleMap.keys) {
    if (!byRole.containsKey(role)) throw StateError('geometry JSON has no "$role" fiducial');
  }
  if (byRole.length != _roleMap.length) {
    throw StateError('geometry JSON has fiducials this importer does not know: '
        '${byRole.keys.where((k) => !_roleMap.containsKey(k))}');
  }
  String corner(String role) {
    final f = byRole[role]!;
    return 'OmrCorner(${_f((f['x'] as num) / w)}, ${_f((f['y'] as num) / h)})';
  }

  final corners = ['topLeft', 'topRight', 'bottomLeft', 'bottomRight'].map(corner).join(', ');
  final interior = [
    for (final e in _roleMap.entries)
      if (e.value != null)
        'OmrFiducial(OmrFiducialRole.${e.value}, ${_f((byRole[e.key]!['x'] as num) / w)}, '
            '${_f((byRole[e.key]!['y'] as num) / h)}, ${(byRole[e.key]!['side'] as num) / 2})',
  ].join(', ');

  // --- bubbles -----------------------------------------------------------
  final bubbles = (data['bubbles'] as List).cast<Map<String, dynamic>>();
  final sectionOrder = <String>[];
  final sections = <String, Map<int, List<Map<String, dynamic>>>>{};
  double rx = 0, ry = 0;
  for (final b in bubbles) {
    final s = b['section'] as String;
    if (!sections.containsKey(s)) sectionOrder.add(s);
    sections.putIfAbsent(s, () => {}).putIfAbsent(b['question'] as int, () => []).add(b);
    rx = (b['rx'] as num).toDouble();
    ry = (b['ry'] as num).toDouble();
  }
  final counts = {for (final s in sectionOrder) s: sections[s]!.length};
  if (counts['Test I'] != 30 || counts['Test II'] != 80 || counts['Test III'] != 20) {
    throw StateError('unexpected question counts $counts (want 30/80/20)');
  }

  // --- name fields ---------------------------------------------------------
  final fields = {
    for (final f in data['fields'] as List) (f as Map<String, dynamic>)['name'] as String: f,
  };
  String rect(String name) {
    final f = fields[name] ?? (throw StateError('geometry JSON has no "$name" field'));
    return 'OmrFieldRect(${_f((f['x'] as num) / w)}, ${_f((f['y'] as num) / h)}, '
        '${_f((f['width'] as num) / w)}, ${_f((f['height'] as num) / h)})';
  }

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/import_tat_v5_geometry.dart from')
    ..writeln('// TAT-portrait-proposed-v5.geometry.json -- do not hand-edit.')
    ..writeln('// Portrait TAT, 8.5 x 13 in (612 x 936 pt): 4 corners, a side pair and a centre')
    ..writeln('// mark at the page midpoint, and 7 small marks above the answer groups.')
    ..writeln('// A separate template version: the earlier TAT layouts stay defined (see')
    ..writeln('// omrTemplateFor) so archived scans keep reading with their own geometry.')
    ..writeln()
    ..writeln("import 'omr_templates.dart';")
    ..writeln()
    ..writeln('final OmrExamTemplate omrTATPortraitV5 = OmrExamTemplate(')
    ..writeln('  examCode: "TAT",')
    ..writeln('  templateVersion: "TAT-portrait-v5",')
    ..writeln('  pageWidthPt: ${w.toStringAsFixed(1)},')
    ..writeln('  pageHeightPt: ${h.toStringAsFixed(1)},')
    ..writeln('  bubbleRadiusPt: $rx,')
    ..writeln('  bubbleRadiusYPt: $ry,')
    ..writeln('  cornerMarkers: const [$corners],')
    ..writeln('  interiorFiducials: const [$interior],')
    ..writeln('  lastNameFieldRect: const ${rect('Last Name')},')
    ..writeln('  firstNameFieldRect: const ${rect('First Name')},')
    ..writeln('  middleNameFieldRect: const ${rect('Middle Name')},')
    ..writeln('  lastNameBoxCount: 0,')
    ..writeln('  firstNameBoxCount: 0,')
    ..writeln('  middleNameBoxCount: 0,')
    ..writeln('  sections: const [');
  for (final s in sectionOrder) {
    out
      ..writeln('    OmrSection(')
      ..writeln('      name: "$s",')
      ..writeln('      itemCount: ${counts[s]},')
      ..writeln('      items: {');
    final items = sections[s]!;
    for (final q in items.keys.toList()..sort()) {
      final cells = items[q]!
          .map((b) => 'BubblePos("${b['choice']}", ${_f((b['x'] as num) / w)}, ${_f((b['y'] as num) / h)})')
          .join(', ');
      out.writeln('        $q: [$cells],');
    }
    out
      ..writeln('      },')
      ..writeln('    ),');
  }
  out
    ..writeln('  ],')
    ..writeln(');');
  File(_outPath).writeAsStringSync(out.toString());
  stdout.writeln('Wrote $_outPath (${bubbles.length} bubbles, ${byRole.length} fiducials)');
}
