"""Emit the A4 TAT scanner geometry from the printable sheet's coordinates."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

def main():
    g = json.loads((ROOT/'tool/data/TAT-A4-placement-v2.geometry.json').read_text())
    w,h = g['pageWidth'],g['pageHeight']
    f = lambda v: f'{v:.8f}'
    corners = [m for m in g['fiducials'] if m['role'] in ('topLeft','topRight','bottomLeft','bottomRight')]
    extras = [m for m in g['fiducials'] if m not in corners]
    roles = dict(aboveUpper0='tatA4AboveI1', aboveUpper1='tatA4AboveI16',
                 aboveUpper2='tatA4AboveIII1', aboveUpper3='tatA4AboveIII11',
                 aboveTestII21='tatAboveII21', aboveTestII41='tatAboveII41')
    out = ['// GENERATED by tool/import_tat_a4_geometry.py. Do not hand-edit.',
           "import 'omr_templates.dart';", '',
           'final OmrExamTemplate omrTATA4V2 = OmrExamTemplate(',
           '  examCode: "TAT",', '  templateVersion: "TAT-A4-placement-v2",',
           f'  pageWidthPt: {w},', f'  pageHeightPt: {h},',
           '  bubbleRadiusPt: 8.0,', '  bubbleRadiusYPt: 5.6,',
           '  cornerMarkers: const [' + ', '.join(f'OmrCorner({f(m["x"]/w)}, {f(m["y"]/h)})' for m in corners) + '],',
           '  interiorFiducials: const [' + ', '.join(f'OmrFiducial(OmrFiducialRole.{roles.get(m["role"],m["role"])}, {f(m["x"]/w)}, {f(m["y"]/h)}, {m["side"]/2})' for m in extras) + '],']
    fields = {v['name']:v for v in g['fields']}
    for attr,name in [('lastNameFieldRect','Last Name'),('firstNameFieldRect','First Name'),('middleNameFieldRect','Middle Name')]:
        v=fields[name]
        out.append(f'  {attr}: const OmrFieldRect({f(v["x"]/w)}, {f(v["y"]/h)}, {f(v["width"]/w)}, {f(v["height"]/h)}),')
    out.append('  sections: const [')
    for name,count in [('Test I',30),('Test II',80),('Test III',20)]:
        out.extend(['    OmrSection(',f'      name: "{name}",',f'      itemCount: {count},','      items: {'])
        for n in range(1,count+1):
            cells=[b for b in g['bubbles'] if b['section']==name and b['question']==n]
            assert len(cells)==(4 if name=='Test I' else 2)
            out.append(f'        {n}: ['+', '.join(f'BubblePos("{b["choice"]}", {f(b["x"]/w)}, {f(b["y"]/h)})' for b in cells)+'],')
        out.extend(['      },','    ),'])
    out.extend(['  ],',');',''])
    (ROOT/'lib/core/omr/omr_template_tat_a4.dart').write_text('\n'.join(out))

if __name__=='__main__': main()
