# google_mlkit_text_recognition references optional per-language recognizer
# classes (Chinese/Devanagari/Japanese/Korean) that this app never actually
# uses -- only the default (Latin) TextRecognizer is called anywhere in the
# codebase. Without these, R8 fails the release build outright (not just a
# warning) because it can't resolve those classes to verify they're safe to
# discard. Generated by Gradle itself into
# build/app/outputs/mapping/release/missing_rules.txt after a failed release
# build; copied here verbatim rather than guessed.
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions

# The -dontwarn rules above only silence R8's compile-time "can't resolve
# this class" error for the per-language recognizer variants this app never
# uses -- they do NOT keep the classes google_mlkit_text_recognition's Latin
# TextRecognizer actually calls at runtime. Without an explicit -keep, R8 is
# free to strip/rename members that the plugin's Java<->Dart method-channel
# bridge and the underlying Play Services ML Kit module reach via
# reflection, which silently breaks OCR in release builds specifically
# (debug builds skip R8 entirely, so this never showed up there) --
# confirmed 2026-09-02: name auto-fill (see
# lib/core/omr/name_ocr_service_native.dart) worked in `flutter run --debug`
# but stayed blank in an otherwise-identical `flutter build apk --release`.
#
# A first attempt only kept vision.text/vision.common and made things worse:
# ML Kit's dependency-injection component registry (com.google.mlkit.common.
# sdkinternal.*, used by every ML Kit vision API, not just text) got stripped
# since it was never listed, and R8 (re)computed a *different* reachable set
# once some mlkit classes were rooted -- the app then crashed on launch
# entirely (MlKitInitProvider failing "Unsatisfied dependency ... com.google.
# mlkit.common.sdkinternal.d"), confirmed via a real device logcat. Keeping
# the whole com.google.mlkit package (not just its vision.text/vision.common
# sub-packages) avoids this whack-a-mole across ML Kit's own internal wiring.
-keep class com.google.mlkit.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_text_common.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_text_bundled_common.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_common.** { *; }
-keep class com.google.android.gms.internal.mlkit_common.** { *; }
