# google_mlkit_text_recognition references optional per-language recognizer
# classes (Chinese/Devanagari/Japanese/Korean) that this app never actually
# uses -- only the default (Latin) TextRecognizer is called anywhere in the
# codebase. Without these, R8 fails the release build outright (not just a
# warning) because it can't resolve those classes to verify they're safe to
# discard. Generated by Gradle itself into
# build/app/outputs/mapping/release/missing_rules.txt after a failed release
# build; copied here verbatim rather than guessed.
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.chinese.ChineseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.devanagari.DevanagariTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions$Builder
-dontwarn com.google.mlkit.vision.text.korean.KoreanTextRecognizerOptions
