/// The fixed set of exams GuideGrade currently supports. Exam designs are
/// not finalized yet, so this is a hardcoded catalog rather than
/// Firestore-backed CRUD -- see omrTemplates for the matching sheet layouts.
class ExamCatalogEntry {
  final String examCode;
  final String title;

  /// The printable OMR bubble sheet examinees actually mark and staff
  /// scan -- generated by tool/generate_sheets.dart, bundled from
  /// answer_sheets/.
  final String pdfAsset;

  /// The exam's actual question booklet (what examinees read), distinct
  /// from [pdfAsset] -- bundled from questionnaires/. Null for an exam
  /// with no questionnaire on file yet; ExamSheetPreviewScreen falls back
  /// to showing only the answer sheet in that case rather than a broken
  /// tab.
  final String? questionnairePdfAsset;

  const ExamCatalogEntry({
    required this.examCode,
    required this.title,
    required this.pdfAsset,
    this.questionnairePdfAsset,
  });
}

const List<ExamCatalogEntry> examCatalog = [
  ExamCatalogEntry(
    examCode: 'AT',
    title: 'Admission Test',
    pdfAsset: 'answer_sheets/AT.pdf',
    questionnairePdfAsset: 'questionnaires/AT.pdf',
  ),
  ExamCatalogEntry(
    examCode: 'QTM',
    title: 'Quantitative Math Test',
    pdfAsset: 'answer_sheets/QTM.pdf',
    questionnairePdfAsset: 'questionnaires/QTM.pdf',
  ),
  ExamCatalogEntry(
    examCode: 'TAT',
    title: 'Teaching Aptitude Test',
    pdfAsset: 'answer_sheets/TAT-portrait-v5.pdf',
    questionnairePdfAsset: 'questionnaires/TAT.pdf',
  ),
];
