/// The fixed set of exams GuideGrade currently supports. Exam designs are
/// not finalized yet, so this is a hardcoded catalog rather than
/// Firestore-backed CRUD -- see omrTemplates for the matching sheet layouts.
class ExamCatalogEntry {
  final String examCode;
  final String title;

  /// The printable OMR bubble sheet examinees actually mark and staff
  /// scan -- generated by tool/generate_sheets.dart, bundled from
  /// answer_sheets/.
  final String pdfAsset;

  /// The exam's actual question booklet (what examinees read), distinct
  /// from [pdfAsset] -- bundled from questionnaires/. Null for an exam
  /// with no questionnaire on file yet; ExamSheetPreviewScreen falls back
  /// to showing only the answer sheet in that case rather than a broken
  /// tab.
  final String? questionnairePdfAsset;

  const ExamCatalogEntry({
    required this.examCode,
    required this.title,
    required this.pdfAsset,
    this.questionnairePdfAsset,
  });
}

const List<ExamCatalogEntry> examCatalog = [
  ExamCatalogEntry(
    examCode: 'AT',
    title: 'Admission Test',
    pdfAsset: 'answer_sheets/AT.pdf',
    questionnairePdfAsset: 'questionnaires/AT.pdf',
  ),
  ExamCatalogEntry(
    examCode: 'QTM',
    title: 'Qualifying Test for Mathematics',
    pdfAsset: 'answer_sheets/QTM.pdf',
    questionnairePdfAsset: 'questionnaires/QTM.pdf',
  ),
  ExamCatalogEntry(
    examCode: 'TAT',
    title: 'Teaching Aptitude Test',
    pdfAsset: 'answer_sheets/TAT-A4-placement-v2.pdf',
    questionnairePdfAsset: 'questionnaires/TAT.pdf',
  ),
];

/// The human-facing "Title (CODE)" label for [examCode], e.g.
/// "Qualifying Test for Mathematics (QTM)" -- the single canonical source
/// every screen showing an exam-type label should read from, instead of
/// its own separately hand-maintained copy of these three names. Falls
/// back to the bare code if [examCode] isn't in [examCatalog] (never
/// throws -- an unrecognized code is a legitimate, if unexpected, value
/// wherever it flows from user or historical data).
///
/// NOT the same string as `lib/core/omr/omr_templates.dart`'s legacy
/// single-section OMR identifier "Qualifying Test in Mathematics" ("in",
/// not "for") -- that's a frozen, historical scan-decoding identifier and
/// must never be derived from or reconciled with this display label.
String examTypeDisplayLabel(String examCode) {
  for (final entry in examCatalog) {
    if (entry.examCode == examCode) return '${entry.title} ($examCode)';
  }
  return examCode;
}
